In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [3]:
df=pd.read_csv("city_day.csv")
df.head()

City        Date  PM2.5  PM10     NO    NO2    NOx  NH3     CO    SO2  \
0  Ahmedabad  2015-01-01    NaN   NaN   0.92  18.22  17.15  NaN   0.92  27.64   
1  Ahmedabad  2015-01-02    NaN   NaN   0.97  15.69  16.46  NaN   0.97  24.55   
2  Ahmedabad  2015-01-03    NaN   NaN  17.40  19.30  29.70  NaN  17.40  29.07   
3  Ahmedabad  2015-01-04    NaN   NaN   1.70  18.48  17.97  NaN   1.70  18.59   
4  Ahmedabad  2015-01-05    NaN   NaN  22.10  21.42  37.76  NaN  22.10  39.33   

       O3  Benzene  Toluene  Xylene  AQI AQI_Bucket  
0  133.36     0.00     0.02    0.00  NaN        NaN  
1   34.06     3.68     5.50    3.77  NaN        NaN  
2   30.70     6.80    16.40    2.25  NaN        NaN  
3   36.08     4.43    10.14    1.00  NaN        NaN  
4   39.31     7.01    18.89    2.78  NaN        NaN

In [4]:
del df['City']

In [5]:
del df['Date']

In [6]:
df.rename(columns={'AQI_Bucket':'Air_Quality'},inplace=True)

In [7]:
df['PM2.5']=df['PM2.5'].fillna((df['PM2.5'].median()))
df['PM10']=df['PM10'].fillna((df['PM10'].median()))
df['NO']=df['NO'].fillna((df['NO'].median()))
df['NO2']=df['NO2'].fillna((df['NO2'].median()))
df['NOx']=df['NOx'].fillna((df['NOx'].median()))
df['NH3']=df['NH3'].fillna((df['NH3'].median()))
df['CO']=df['CO'].fillna((df['CO'].median()))
df['SO2']=df['SO2'].fillna((df['SO2'].median()))
df['O3']=df['O3'].fillna((df['O3'].median()))
df['Benzene']=df['Benzene'].fillna((df['Benzene'].median()))
df['Toluene']=df['Xylene'].fillna((df['Xylene'].median()))
df['Xylene']=df['PM2.5'].fillna((df['PM2.5'].median()))
df['AQI']=df['AQI'].fillna((df['AQI'].median()))
df['Air_Quality']=df['Air_Quality'].fillna('Moderate')

In [8]:
indepvar=[]
for i in df.columns:
  if i!='Air_Quality':
    indepvar.append(i)
targetvar=df['Air_Quality']
x=df[indepvar]
y=targetvar

In [9]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [11]:
from xgboost import XGBClassifier
m=XGBClassifier(n_estimators=20,random_state=23)
m.fit(x_train,y_train)
m_pred=m.predict(x_test)
m_cm=confusion_matrix(y_test,m_pred)
m_as=accuracy_score(y_test,m_pred)
print("confusion matrix")
print(m_cm)
print("\n")
print("accuracy: ",m_as*100)


confusion matrix
[[ 393    0    0    0    0    0]
 [   0 4117    0    0    0    0]
 [   0    0  841    0    0    0]
 [   0    0    0 2425    0    0]
 [   0    0    0    0  381    0]
 [   0    0    0    0    0  703]]


accuracy:  100.0


In [12]:
pickle.dump(m,open('air.pkl','wb'))